openapi: 3.0.4
info:
  title: Technical objects for YeenCloud
  version: "1.0.0"

components:
  schemas:
    ResponseError:
      type: object
      properties:
        code:
          type: string
          nullable: true
        message:
          type: string
        howToFix:
          type: string
          nullable: true
      required:
        - message

    Response:
      type: object
      properties:
        status:
          type: integer
        body:
          type: object
        error:
          $ref: '#/components/schemas/ResponseError'
        requestId:
          type: string
        correlationId:
          type: string
      required:
        - status